# options for Quarto book
# https://quarto.org/docs/reference/projects/books.html
# 
# Options for html
# https://quarto.org/docs/reference/projects/websites.html#section

project:
  type: book
  output-dir: docs



book:
  title: "Demographics and Dating Apps: How User Interaction Varies by Group in Simulated Dating Software"
  author: ["Francesca LoPresti", "Maren Stewart-Tanner", "Providence Thusabantu", "El Davis-Greene"]
  date: today  # use today to update date published based on last time project was edited
  date-format: full
  # favicon: images/logo.png
  reader-mode: true
  # site-url: https://hashcx.github.io/mac-comp112website-f24/
  page-navigation: true
  back-to-top-navigation: true
  cookie-consent: true
  # bread-crumbs: true  # causes problems with older Quarto version
  # downloads: [pdf]
  # repo-url: https://github.com/hashcx/mac-comp112website-f24
  # repo-actions: [edit, issue]
  # repo-link-target: "_blank" #makes issue and edit links open in a new window/tab 


  sidebar:
    title: "Demographics and Dating Apps"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true

  chapters:
    - index.qmd
    
    - part: "Effective Teamwork Readings"
      chapters: 
      - src/appx/Maren-ST.qmd
      - src/appx/Providence-T.qmd
      - src/appx/Francesca-L.qmd
      - src/appx/ElDG.qmd
    
    - part: "EDA"
      chapters: 
        - src/EDA/Maren-ST.qmd
        - src/EDA/Francesca-L.qmd
        - src/EDA/EDG_EDA.qmd
  
    - part: "Analysis"
      chapters: 
        - analysis/income.qmd
        - analysis/location.qmd
        - analysis/gender.qmd
        - analysis/orientation.qmd
        - analysis/tags.qmd
        - analysis/education.qmd
        
  appendices:
  - src/appx/proposal.qmd
  - src/appx/case-study.qmd



format:
  html:
    theme: # bootswatch themes--other options https://bootswatch.com/
      light: flatly
      dark: darkly
    search: true
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    smooth-scroll: true
    code-overflow: scroll
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#1482FA"
    code-tools: true
    page-layout: full

  # pdf:
  #   documentclass: scrreprt
  #   keep-tex: false



execute:
  cache: true
#   freeze: auto # remove when using GitHub action to execute code



editor: 
  mode: source
  markdown:
    wrap: sentence # Forces each sentence to be on its own line in source markdown, however, it doesn't affect how it is rendered
