---
title: "Report"
format: html
---
**Load Packages**
```{r}
library(tidyverse)
library(viridis)
```

**Load dataset**
```{r}
dating_app_data <- read.csv('../data/dating_app_behavior_dataset.csv')
```

### Gender

let's look at user labels. 

```{r}
dating_app_data |>
  mutate(app_usage_time_label = fct_relevel(app_usage_time_label,
            "Addicted", "Extreme User", "High", "Moderate", "Barely", "Low", "Very Low")) |>
  ggplot(aes(y = gender, fill = app_usage_time_label)) +
  geom_bar(position = "fill") +
  labs(fill = "Usage", y = "Gender") +
  scale_fill_viridis_d() 
```
The visualization above indicates that the largest usage tag for every gender is "Extreme user". Now lets look at the "Addicted" category.

```{r, fig.height=5, fig.width=10}
dating_app_data |>
  filter(app_usage_time_label == "Addicted") |>
  group_by(gender) |>
  summarize(count = n()) |>
ggplot(aes(y = gender, x = count, fill = gender)) +
  geom_col() +
  scale_fill_viridis_d()
```
So nonbinary users and those who prefer not to say are the largest groups categorized as Addicted.
